from affine.detection.model_worker.serializer import DEFAULT_PICKLE_NAME

DEFAULT_QUEUE = 'celery'

class BaseConfig(object):
    CELERY_TASK_RESULT_EXPIRES=120
    CELERY_TASK_SERIALIZER = DEFAULT_PICKLE_NAME
    CELERY_RESULT_SERIALIZER = DEFAULT_PICKLE_NAME
    CELERY_MESSAGE_COMPRESSION = 'bzip2'
    CELERY_REDIS_SOCKET_TIMEOUT = 5
